version: 2.0

jobs:
  deploy-snapshot:
    docker:
      - image: circleci/openjdk:8-jdk-stretch-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: |
          ./mvnw -s .circleci.settings.xml -Dmaven.test.skip=true deploy
  test:
    docker:
      - image: circleci/openjdk:8-jdk-stretch-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: |
          ./mvnw -s .circleci.settings.xml test verify
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: ./mvnw -s .circleci.settings.xml -Dmaven.test.skip=true package
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy-snapshot:
          requires:
            - test
